FROM python:3.8

COPY . /usr/src/
WORKDIR /usr/src

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r Requiriments.txt

EXPOSE 5001

RUN export FLASK_APP=app.py

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]